import type { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMoon,
  HiSun,
  HiOutlineDocument,
  HiOutlinePencilSquare,
  HiOutlineExclamationTriangle,
  HiOutlineArrowTopRightOnSquare,
  HiUsers,
  HiCodeBracket,
  HiOutlineStar,
  HiOutlineFaceSmile,
  HiStar,
  HiOutlineMagnifyingGlass,
  HiBriefcase,
  HiShoppingCart,
  HiArrowRightCircle
} from "react-icons/hi2";

import { GoRepoForked } from "react-icons/go";
import { IoIosConstruct } from "react-icons/io";
import { IoAtOutline, IoFastFoodOutline, IoFlagOutline, IoFootballOutline, IoGiftOutline, IoGlobeOutline, IoImages, IoPawOutline, IoPencil, IoSettingsOutline, IoShieldCheckmark, IoSparkles } from "react-icons/io5";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiPaletteBold,
  PiDeviceMobile,
  PiUpload,
  PiLightbulbDuotone,
} from "react-icons/pi";

import { FaDiscord, FaEuroSign, FaGithub, FaX, FaMapPin, FaHandshake, FaChartLine } from "react-icons/fa6";
import { FiBarChart2, FiFacebook, FiFilter, FiLayout, FiLinkedin, FiPackage, FiShare2, FiTrendingUp, FiTruck, FiTwitter, FiZap } from "react-icons/fi";
import { RxCookie } from "react-icons/rx";
import { MdNotificationsNone, MdOutlineNotificationsOff, MdOutlineNotificationsActive } from "react-icons/md";
import { ChevronsLeftRight } from "lucide-react";

export const iconLibrary: Record<string, IconType> = {
  notifNone: MdNotificationsNone,
  notifOff: MdOutlineNotificationsOff,
  notifOn: MdOutlineNotificationsActive,
  facebook: FiFacebook,
  twitter: FiTwitter,
  linkedin: FiLinkedin,
  repondre: HiOutlinePencilSquare,
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  x: FaX,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  moon: HiMoon,
  sun: HiSun,
  document: HiOutlineDocument,
  danger: HiOutlineExclamationTriangle,
  linkblank: HiOutlineArrowTopRightOnSquare,
  users: HiUsers,
  star: HiOutlineStar,
  starfill: HiStar,
  gitfork: GoRepoForked,
  code: HiCodeBracket,
  smile: HiOutlineFaceSmile,
  search: HiOutlineMagnifyingGlass,
  smiley: HiOutlineFaceSmile,
  paw: IoPawOutline,
  food: IoFastFoodOutline,
  ball: IoFootballOutline,
  world: IoGlobeOutline,
  gift: IoGiftOutline,
  symbol: IoAtOutline,
  flag: IoFlagOutline,
  cookie: RxCookie,
  briefcase: HiBriefcase,
  shoppingCart: HiShoppingCart,
  palette: PiPaletteBold,
  mobile: PiDeviceMobile,
  shield: IoShieldCheckmark,
  euro: FaEuroSign,
  construction: IoIosConstruct,
  images: IoImages,
  zap: FiZap,
  settings: IoSettingsOutline,
  share2: FiShare2,
  "bar-chart-2": FiBarChart2,
  "chart-line": FaChartLine,
  pen: IoPencil,
  upload: PiUpload,
  sparkles: IoSparkles,
  lightbulb: PiLightbulbDuotone,
  package: FiPackage,
  "arrow-right-circle": HiArrowRightCircle,
  truck: FiTruck,
  filter: FiFilter,
  "trending-up": FiTrendingUp,
  layout: FiLayout,
  pin: FaMapPin,
  handshake: FaHandshake,
  chevronsLeftRight: ChevronsLeftRight

};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;